name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-world:$(date)
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ashutoshm10docker
        password: Ashutosh@123
    - name: Push the Docker image to Docker Hub
      run: |
        docker commit hello-world:$(date)
        docker tag hello-world:$(date) ashutoshm10docker/hello-world:latest
        docker push ashutoshm10docker/hello-world:latest
